#!/bin/sh

. ~/repositories/dotfiles/git/git-prompt.sh

alias cp='cp -rf'
alias feh='feh -dF'
alias ftp='ftp -p'
alias grep='grep --color=auto'
alias ln='ln -srnf'
alias logout='swaymsg exit'
alias ls='ls -A --color=auto --group-directories-first'
alias lscheckout='pacman -Qkk | grep \)$ |& sort'
alias lsdisowned='comm -23 <(find /{etc,usr,var} \( -path /etc/\*cert\* -o -path /usr/share/mime -o -path /var/\*/\*man \) -prune -o -type d -printf %p/\\n -o -print 2>/dev/null | sort) <(pacman -Qlq | sort -u)'
alias lsorphaned='comm -23 <(pacman -Qdq) <(pacman -Qeq | xargs -l pactree -lu | sed -E "s/[<=>].+//" | sort -u)'
alias lspackages='pacman -Qeq'
alias mkdir='mkdir -p'
alias output-analog='pacmd set-default-sink alsa_output.pci-0000_00_1f.3.analog-stereo'
alias output-hdmi='pacmd set-default-sink alsa_output.hw_0_7'
alias pacman='pacman --color=auto'
alias rm='rm -rf'
alias sl=systemctl
alias sudo='sudo '
alias wallpaper='feh --bg-tile --no-fehbg'

fetchallgit() {
  find ~/VRChat-avatars/{.*,*}/.git -maxdepth 0 -execdir git fetch --all \;
  find ~/repositories/*/.git -maxdepth 0 -execdir git fetch --all \;
}

gcallgit() {
  find ~/VRChat-avatars/{.*,*}/.git -maxdepth 0 -execdir git reflog expire --expire=now --all \;
  find ~/VRChat-avatars/{.*,*}/.git -maxdepth 0 -execdir git gc --prune=now --aggressive \;
  find ~/repositories/*/.git -maxdepth 0 -execdir git reflog expire --expire=now --all \;
  find ~/repositories/*/.git -maxdepth 0 -execdir git gc --prune=now --aggressive \;
}

gdrive_dl() {
  local file_id=$1
  local file_name=$2
  curl -sc /tmp/cookie "https://drive.google.com/uc?export=download&id=${file_id}" >/dev/null
  local code="$(awk '/_warning_/ {print $NF}' /tmp/cookie)"
  curl -Lb /tmp/cookie "https://drive.google.com/uc?export=download&confirm=${code}&id=${file_id}" -o "$file_name"
}

letsencrypt() {
  local domain_name=$1
  sudo certbot certonly \
    --agree-tos \
    --manual \
    --manual-auth-hook ~kuroclef/repositories/letsencrypt-dns-conoha/create_conoha_dns_record.sh \
    --manual-cleanup-hook ~kuroclef/repositories/letsencrypt-dns-conoha/delete_conoha_dns_record.sh \
    --manual-public-ip-logging-ok \
    --preferred-challenges dns-01 \
    --server https://acme-v02.api.letsencrypt.org/directory \
    -d "$domain_name" -d \*."$domain_name" \
    -m kuroclef@gmail.com
}

lsgit() {
  sh <<-\EOL
    . ~/repositories/dotfiles/git/git-prompt.sh
    export -f __git_eread __git_ps1 __git_ps1_show_upstream __git_sequencer_status
    find ~/VRChat-avatars/{.*,*}/.git -maxdepth 0 -execdir sh -c '__git_ps1 "%s \t"; basename "$PWD"' \;
    find ~/repositories/*/.git -maxdepth 0 -execdir sh -c '__git_ps1 "%s \t"; basename "$PWD"' \;
EOL
}

resetallgit() {
  find ~/repositories/*/.git -maxdepth 0 -execdir \
    sh -c 'git reset --hard origin/"$(git symbolic-ref --short HEAD)"' \;
}

updatevrcsdk() {
  find ~/VRChat-avatars/*/.git -maxdepth 0 -execdir \
    sh -c 'git rebase template-SDK3/master; git rebase --skip; git filter-date; rm -r Packages; cp -r ../.template-SDK3/Packages .' \;
}
