#!/bin/bash

cd "$(dirname "$(readlink -f "$0")")"

find alacritty fontconfig git gtk-3.0 i3status-rust sway wlxoverlay -prune -exec ln -srnf {} ~/.config/{} \;
find vim zprofile zshrc -maxdepth 0 -exec ln -srnf {} ~/.{} \;
ln -srnf gtk-3.0 ~/.config/gtk-4.0

[ -f ~/.vim/autoload/plug.vim ] && exit
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
