#!/bin/bash

cd -P .
mkdir -p ~/.config
ln -snf "$PWD"/{alacritty,fontconfig,git,gtk-3.0,i3status-rust,sway,wayvr} ~/.config
ln -snf "$PWD"/gtk-3.0 ~/.config/gtk-4.0
ln -snf "$PWD"/profile ~/.bash_profile
ln -snf "$PWD"/profile ~/.zprofile
ln -snf "$PWD"/rc      ~/.bashrc
ln -snf "$PWD"/rc      ~/.zshrc
ln -snf "$PWD"/vim     ~/.vim

[ -f ~/.vim/autoload/plug.vim ] && exit
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
