set background=dark
set backspace=indent,eol,start
set display=lastline
set encoding=utf-8
set expandtab
set fileencodings=utf-8,cp932
set ignorecase
set laststatus=2
set list
set listchars=tab:»\ ,trail:\ ,
set pumheight=10
set scrolloff=2
set shiftwidth=2
set smartcase
set softtabstop=2
set statusline=%f\ %r%m%=0x%B\ %l/%L\ %{&fenc.','.&ff}\ %y
set tabstop=2
set viminfo=
set wildignore=*.od*,*.pdf
set wildignorecase
set wildmode=list:longest,full
set nowrap
syntax on

cnoremap % <C-u>%s/\v

inoremap <expr><CR>  pumvisible() ? "<C-y>" : "<CR>"
inoremap <expr><BS>  pumvisible() ? "<C-e>" : "<BS>"
inoremap <expr><Tab> pumvisible() ? "<C-n>" : "<C-n><C-p>"

nnoremap j       gj
nnoremap k       gk
nnoremap Y       y$
nnoremap /       /\v
nnoremap <CR>    o<Esc>
nnoremap <TAB>   <C-w>
nnoremap <Space> i<Space><Esc>

augroup _
  autocmd!
  autocmd FileType cpp        call s:ccSetup()
  autocmd FileType javascript call s:jsSetup()
  autocmd FileType man        setl nolist
  autocmd FileType tex        call s:texSetup()
  autocmd ColorScheme,VimEnter * highlight StatusLine   cterm=NONE gui=NONE
  autocmd ColorScheme,VimEnter * highlight StatusLineNC cterm=NONE gui=NONE
augroup END

function! s:ccSetup()
  syntax match Constant /\v<\u[A-Z_]+>/
  syntax match Function /\v<\h\w*>\ze\(/
  syntax match Type     /\v<\u\l\h*>\ze[^(]|<\u+>|<string>/
endfunction

function! s:jsSetup()
  syntax match Constant /\v<\u[A-Z_]+>/
  syntax match Function /\v<\h\w*>\ze[\(`]/
  highlight link javaScriptIdentifier Type
  highlight link javaScriptNumber     Number
endfunction

function! s:texSetup()
  unlet g:loaded_matchparen
  runtime plugin/matchparen.vim
endfunction

let g:eskk#dictionary        = "/dev/null"
let g:eskk#directory         = "/dev/null"
let g:eskk#egg_like_newline  = 1
let g:eskk#large_dictionary  = "/usr/share/skk/SKK-JISYO.L.neologd"
let g:loaded_matchparen      = 1
let g:loaded_netrw           = 1
let g:loaded_netrwPlugin     = 1
let g:rust_recommended_style = 0
runtime ftplugin/man.vim
filetype plugin indent on

if &t_Co == 256 || has("gui_running")
  let g:solarized_termtrans = 1
  colorscheme solarized
endif
