icons = "awesome"
theme = "native"

[[block]]
block = "music"
buttons = [ "play", "next" ]
dynamic_width = true
format = "{title}"
max_width = 128
player = "mpd"

[[block]]
block = "sound"
format = "{output_name}{volume}"
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "\uf109"
#"alsa_output.hw_0_7" = "\uf108"
"alsa_output.hw_0_7" = "\uf26c"

[[block]]
block = "backlight"

[[block]]
block  = "net"
format = "{ssid}"

[[block]]
block = "battery"
device = "DisplayDevice"
driver = "upower"
format = "{percentage} {time}"

[[block]]
block = "time"
format = "%F %a %R"
interval = 1
